#!/bin/sh

mkdir components
mkdir component-addform
mkdir component-alternating-gate
mkdir component-audio
mkdir component-boolean
mkdir component-button
mkdir component-button-with-confirmation
mkdir component-camera-button
mkdir component-canvas
mkdir component-chart
mkdir component-chat-window
mkdir component-combiner
mkdir component-counter
mkdir component-cowbell
mkdir component-daily-counter
mkdir component-dataview
mkdir component-editform
mkdir component-fireworks
mkdir component-header
mkdir component-hot-potato
mkdir component-image
mkdir component-jazzhands
mkdir component-kickdrum
mkdir component-meatspaces-input
mkdir component-meatspaces-messages
mkdir component-metronome
mkdir component-microphone-button
mkdir component-paypal
mkdir component-random-number
mkdir component-sequencer
mkdir component-snaredrum
mkdir component-spacer
mkdir component-splitter
mkdir component-text-input
mkdir component-textbox
mkdir component-transformer
mkdir component-pad-grid
mkdir component-notebook
mkdir component-channel-gate
mkdir component-double-button
mkdir component-todo
mkdir component-game-controller
